name = "Plinf"
uuid = "3f517155-95b4-4010-b517-e038c017d66c"
authors = ["Xuan <tanqazx@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
Julog = "5d8bcb5e-2b2c-4a96-a2b1-d40b3d3c344f"
PDDL = "2c8894f9-daa1-498a-9e3a-26edd9623db8"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"

[compat]
Julog = "^0.1.2
