name = "Plinf"
uuid = "3f517155-95b4-4010-b517-e038c017d66c"
authors = ["Xuan <tanqazx@gmail.com>"]
version = "0.3.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
GenParticleFilters = "56b76ac4-72ef-411e-b419-6d312ed86a6f"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Julog = "5d8bcb5e-2b2c-4a96-a2b1-d40b3d3c344f"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
PDDL = "2c8894f9-daa1-498a-9e3a-26edd9623db8"
PDDLViz = "8f72e95f-8ea1-4af3-8b89-086f52abff52"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SymbolicPlanners = "b6fe5377-9711-4fad-95b0-be4eed71ecbb"

[compat]
Gen = "0.4.5"
GenParticleFilters = "0.2.0"
PDDL = "0.2.13"
SymbolicPlanners = "0.1.12"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
