name = "Plinf"
uuid = "3f517155-95b4-4010-b517-e038c017d66c"
authors = ["Xuan <tanqazx@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
GenParticleFilters = "56b76ac4-72ef-411e-b419-6d312ed86a6f"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Julog = "5d8bcb5e-2b2c-4a96-a2b1-d40b3d3c344f"
LazyJSON = "fc18253b-5e1b-504c-a4a2-9ece4944c004"
PDDL = "2c8894f9-daa1-498a-9e3a-26edd9623db8"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
Gen = "0.4"
Julog = "0.1.4"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
